/* global SUBJECTS */
// Generated by scripts/generate-rank03-data.mjs from subjects/rank03/
var SUBJECTS = [
  {
    id: 1,
    difficulty: "medium",
    name: "py_number_base_converter",
    file: "py_number_base_converter.py",
    description: {
      en: "Write a function that converts a number from one base to another.\nSupport bases from 2 to 36 inclusive, using digits 0-9 and letters A-Z for values 10-35. Return \"ERROR\" for invalid inputs (base, digits)",
      de: "Schreibe eine Funktion, die eine Zahl von einer Basis in eine andere konvertiert.\nUnterstütze Basen von 2 bis 36 einschließlich, mit Ziffern 0-9 und Buchstaben A-Z für die Werte 10-35. Gib bei ungültigen Eingaben (Basis, Ziffern) \"ERROR\" zurück.",
      fr: "Écris une fonction qui convertit un nombre d'une base vers une autre.\nPrends en charge les bases de 2 à 36 inclus, avec les chiffres 0-9 et les lettres A-Z pour les valeurs 10-35. Renvoie \"ERROR\" pour les entrées invalides (base, chiffres).",
      es: "Escribe una función que convierta un número de una base a otra.\nAdmite bases de 2 a 36 inclusive, usando dígitos 0-9 y letras A-Z para los valores 10-35. Devuelve \"ERROR\" si la entrada no es válida (base, dígitos).",
      it: "Scrivi una funzione che converta un numero da una base a un'altra.\nSupporta basi da 2 a 36 inclusive, usando cifre 0-9 e lettere A-Z per i valori 10-35. Restituisci \"ERROR\" per input non validi (base, cifre).",
    },
    signature: "def number_base_converter(number: str, from_base: int, to_base: int) -> str:",
    examples: [
        {
          "input": "number_base_converter(\"1010\", 2, 10)",
          "output": "\"10\""
        },
        {
          "input": "number_base_converter(\"FF\", 16, 10)",
          "output": "\"255\""
        },
        {
          "input": "number_base_converter(\"255\", 10, 16)",
          "output": "\"FF\""
        },
        {
          "input": "number_base_converter(\"123\", 10, 2)",
          "output": "\"1111011\""
        },
        {
          "input": "number_base_converter(\"Z\", 36, 10)",
          "output": "\"35\""
        },
        {
          "input": "number_base_converter(\"35\", 10, 36)",
          "output": "\"Z\""
        },Grademe-edu
        {
          "input": "number_base_converter(\"123\", 1, 10)",
          "output": "\"ERROR\""
        },
        {
          "input": "number_base_converter(\"G\", 16, 10)",
          "output": "\"ERROR\""
        }
      ],
  },
  {
    id: 2,
    difficulty: "easy",
    name: "py_mirror_matrix",
    file: "py_mirror_matrix.py",
    description: {
      en: "Write a function that mirrors a 2D matrix horizontally by reversing each row.",
      de: "Schreibe eine Funktion, die eine 2D-Matrix horizontal spiegelt, indem jede Zeile umgekehrt wird.\n\nDie Funktion soll:\n- Eine 2D-Liste (Matrix) aus ganzen Zahlen als Eingabe nehmen\n- Eine neue 2D-Liste zurückgeben, in der jede Zeile horizontal umgekehrt ist\n- Matrizen beliebiger Größe (quadratisch oder rechteckig) verarbeiten\n- Die ursprüngliche Zeilenreihenfolge beibehalten\n- Die ursprüngliche Matrix nicht verändern",
      fr: "Écris une fonction qui miroite une matrice 2D horizontalement en inversant chaque ligne.\n\nLa fonction doit :\n- Prendre une liste 2D (matrice) d’entiers en entrée\n- Retourner une nouvelle liste 2D où chaque ligne est inversée horizontalement\n- Gérer des matrices de toute taille (carrées ou rectangulaires)\n- Conserver l’ordre d’origine des lignes\n- Ne pas modifier la matrice d’origine",
      es: "Escribe una función que espeje una matriz 2D horizontalmente invirtiendo cada fila.\n\nLa función debe:\n- Recibir una lista 2D (matriz) de enteros\n- Devolver una nueva lista 2D donde cada fila esté invertida horizontalmente\n- Manejar matrices de cualquier tamaño (cuadradas o rectangulares)\n- Conservar el orden original de las filas\n- No modificar la matriz original",
      it: "Scrivi una funzione che specchia una matrice 2D in orizzontale invertendo ogni riga.\n\nLa funzione deve:\n- Prendere in input una lista 2D (matrice) di interi\n- Restituire una nuova lista 2D in cui ogni riga è invertita orizzontalmente\n- Gestire matrici di qualsiasi dimensione (quadrate o rettangolari)\n- Preservare l’ordine originale delle righe\n- Non modificare la matrice originale",
    },
    signature: "def mirror_matrix(matrix: list[list[int]]) -> list[list[int]]:",
    examples: [
        {
          "input": "mirror_matrix([[1, 2, 3], [4, 5, 6]])",
          "output": "[[3, 2, 1], [6, 5, 4]]"
        },
        {
          "input": "mirror_matrix([[1, 2], [3, 4], [5, 6]])",
          "output": "[[2, 1], [4, 3], [6, 5]]"
        },
        {
          "input": "mirror_matrix([[7]])",
          "output": "[[7]]"
        },
        {
          "input": "mirror_matrix([[1, 2, 3, 4]])",
          "output": "[[4, 3, 2, 1]]"
        },
        {
          "input": "mirror_matrix([[-1, -2], [-3, -4]])",
          "output": "[[-2, -1], [-4, -3]]"
        }
      ],
  },
  {
    id: 3,
    difficulty: "medium",
    name: "py_bracket_validator",
    file: "py_bracket_validator.py",
    description: {
      en: "Write a function that checks if brackets [], parentheses (), and braces {} are properly\nbalanced and correctly nested in a string. All others characters are ignored. Return True if balanced, False otherwise",
      de: "Schreibe eine Funktion, die prüft, ob Klammern in einem String korrekt gepaart und geschachtelt sind.\nUnterstütze drei Arten: (), [], {}.\n\nDie Funktion soll:\n- True zurückgeben, wenn alle Klammern korrekt gepaart sind\n- True für Strings ohne Klammern zurückgeben\n- False bei nicht passenden oder falsch geschachtelten Klammern zurückgeben\n- Zeichen außerhalb von Klammern ignorieren",
      fr: "Écris une fonction qui vérifie si les parenthèses d’une chaîne sont correctement appariées et imbriquées.\nPrends en charge trois types : (), [], {}.\n\nLa fonction doit :\n- Retourner True si toutes les parenthèses sont correctement appariées\n- Retourner True pour les chaînes sans aucune parenthèse\n- Retourner False si elles ne correspondent pas ou sont mal imbriquées\n- Ignorer les caractères qui ne sont pas des parenthèses",
      es: "Escribe una función que compruebe si los paréntesis de una cadena están bien emparejados y anidados.\nAdmite tres tipos: (), [], {}.\n\nLa función debe:\n- Devolver True si todos los paréntesis están bien emparejados\n- Devolver True si la cadena no tiene paréntesis\n- Devolver False si faltan pares o el anidamiento es incorrecto\n- Ignorar caracteres que no sean paréntesis",
      it: "Scrivi una funzione che verifichi se le parentesi in una stringa sono accoppiate e annidate correttamente.\nSupporta tre tipi: (), [], {}.\n\nLa funzione deve:\n- Restituire True se tutte le parentesi sono corrette\n- Restituire True per stringhe senza parentesi\n- Restituire False se mancano coppie o l’annidamento è errato\n- Ignorare i caratteri che non sono parentesi",
    },
    signature: "def bracket_validator(s: str) -> bool:",
    examples: [
        {
          "input": "bracket_validator(\"()\")",
          "output": "True"
        },
        {
          "input": "bracket_validator(\"()[]{}\")",
          "output": "True"
        },
        {
          "input": "bracket_validator(\"(]\")",
          "output": "False"
        },
        {
          "input": "bracket_validator(\"([)]\")",
          "output": "False"
        },
        {
          "input": "bracket_validator(\"{[]}\")",
          "output": "True"
        },
        {
          "input": "bracket_validator(\"hello(world)[test]{code}\")",
          "output": "True"
        },
        {
          "input": "bracket_validator(\"((()))\")",
          "output": "True"
        },
        {
          "input": "bracket_validator(\"((())\")",
          "output": "False"
        },
        {
          "input": "bracket_validator(\"\")",
          "output": "True"
        }
      ],
  },
  {
    id: 4,
    difficulty: "easy",
    name: "py_echo_validator",
    file: "py_echo_validator.py",
    description: {
      en: "Write a function that checks if a string is a palindrome, ignoring spaces and case, only consider alphabetic characters for the comparison. The funct",
      de: "Schreibe eine Funktion, die prüft, ob ein String ein Palindrom ist - Leerzeichen und Groß-/Kleinschreibung ignorieren; nur alphabetische Zeichen für den Vergleich berücksichtigen.",
      fr: "Écris une fonction qui vérifie si une chaîne est un palindrome, en ignorant espaces et casse, et en ne considérant que les caractères alphabétiques pour la comparaison.",
      es: "Escribe una función que compruebe si una cadena es un palíndromo, ignorando espacios y mayúsculas/minúsculas, y considerando solo caracteres alfabéticos en la comparación.",
      it: "Scrivi una funzione che verifichi se una stringa è palindroma, ignorando spazi e maiuscole/minuscole e considerando solo i caratteri alfabetici nel confronto.",
    },
    signature: "def echo_validator(text: str) -> bool:",
    examples: [
        {
          "input": "echo_validator(\"racecar\")",
          "output": "True"
        },
        {
          "input": "echo_validator(\"A man a plan a canal Panama\")",
          "output": "True"
        },
        {
          "input": "echo_validator(\"race a car\")",
          "output": "False"
        },
        {
          "input": "echo_validator(\"Was it a car or a cat I saw\")",
          "output": "True"
        },
        {
          "input": "echo_validator(\"hello\")",
          "output": "False"
        },
        {
          "input": "echo_validator(\"Madam Im Adam\")",
          "output": "True"
        },
        {
          "input": "echo_validator(\"\")",
          "output": "False"
        }
      ],
  },
  {
    id: 5,
    difficulty: "hard",
    name: "py_string_permutation_checker",
    file: "py_string_permutation_checker.py",
    description: {
      en: "Write a function that determines if two strings are permutations of each other.\nTwo strings are permutations if they contain the same characters with the same frequencies.",
      de: "Schreibe eine Funktion, die feststellt, ob zwei Strings Permutationen voneinander sind.\nZwei Strings sind Permutationen, wenn sie dieselben Zeichen mit denselben Häufigkeiten enthalten.\n\nDie Funktion soll:\n- Prüfen, ob beide Strings genau dieselben Zeichen enthalten\n- Zeichenhäufigkeiten zählen (groß-/kleinschreibungssensitiv)\n- True zurückgeben, wenn es Permutationen sind, sonst False\n- Leere Strings behandeln (zwei leere Strings sind Permutationen)\n- Leerzeichen und Satzzeichen wie normale Zeichen behandeln",
      fr: "Écris une fonction qui détermine si deux chaînes sont des permutations l’une de l’autre.\nDeux chaînes sont des permutations si elles contiennent les mêmes caractères avec les mêmes fréquences.\n\nLa fonction doit :\n- Vérifier que les deux chaînes contiennent exactement les mêmes caractères\n- Compter les fréquences (sensible à la casse)\n- Retourner True si ce sont des permutations, sinon False\n- Gérer les chaînes vides (deux chaînes vides sont des permutations)\n- Traiter espaces et ponctuation comme des caractères normaux",
      es: "Escribe una función que determine si dos cadenas son permutaciones entre sí.\nDos cadenas son permutaciones si contienen los mismos caracteres con las mismas frecuencias.\n\nLa función debe:\n- Comprobar que ambas cadenas tienen exactamente los mismos caracteres\n- Contar frecuencias (distingue mayúsculas y minúsculas)\n- Devolver True si son permutaciones, False en caso contrario\n- Manejar cadenas vacías (dos vacías son permutación)\n- Tratar espacios y puntuación como caracteres normales",
      it: "Scrivi una funzione che determini se due stringhe sono permutazioni l’una dell’altra.\nDue stringhe sono permutazioni se contengono gli stessi caratteri con le stesse frequenze.\n\nLa funzione deve:\n- Verificare che entrambe le stringhe contengano esattamente gli stessi caratteri\n- Contare le frequenze (case-sensitive)\n- Restituire True se sono permutazioni, altrimenti False\n- Gestire stringhe vuote (due vuote sono permutazioni)\n- Considerare spazi e punteggiatura come caratteri normali",
    },
    signature: "def string_permutation_checker(s1: str, s2: str) -> bool:",
    examples: [
        {
          "input": "string_permutation_checker(\"abc\", \"bca\")",
          "output": "True"
        },
        {
          "input": "string_permutation_checker(\"abc\", \"def\")",
          "output": "False"
        },
        {
          "input": "string_permutation_checker(\"listen\", \"silent\")",
          "output": "True"
        },
        {
          "input": "string_permutation_checker(\"hello\", \"bello\")",
          "output": "False"
        },
        {
          "input": "string_permutation_checker(\"\", \"\")",
          "output": "True"
        },
        {
          "input": "string_permutation_checker(\"a\", \"\")",
          "output": "False"
        },
        {
          "input": "string_permutation_checker(\"Abc\", \"abc\")",
          "output": "False"
        },
        {
          "input": "string_permutation_checker(\"a gentleman\", \"elegant man\")",
          "output": "True"
        }
      ],
  },
  {
    id: 6,
    difficulty: "easy",
    name: "py_whisper_cipher",
    file: "py_whisper_cipher.py",
    description: {
      en: "Write a function that creates a simple cipher by shifting letters in a st\nby a given amount. Non-alphabetic characters should remain unchanged.",
      de: "Schreibe eine Funktion, die eine einfache Verschlüsselung erzeugt, indem Buchstaben in einem String um einen gegebenen Betrag verschoben werden. Nicht-alphabetische Zeichen bleiben unverändert.",
      fr: "Écris une fonction qui réalise un chiffrement simple en décalant les lettres d’une chaîne d’un montant donné. Les caractères non alphabétiques restent inchangés.",
      es: "Escribe una función que cree un cifrado simple desplazando las letras de una cadena una cantidad dada. Los caracteres no alfabéticos deben permanecer iguales.",
      it: "Scrivi una funzione che crei una cifratura semplice spostando le lettere di una stringa di una quantità data. I caratteri non alfabetici restano invariati.",
    },
    signature: "def whisper_cipher(text: str, shift: int) -> str:",
    examples: [
        {
          "input": "whisper_cipher(\"hello\", 3)",
          "output": "\"khoor\""
        },
        {
          "input": "whisper_cipher(\"Hello World!\", 1)",
          "output": "\"Ifmmp Xpsme!\""
        },
        {
          "input": "whisper_cipher(\"xyz\", 3)",
          "output": "\"abc\""
        },
        {
          "input": "whisper_cipher(\"ABC123def\", 5)",
          "output": "\"FGH123ijk\""
        },
        {
          "input": "whisper_cipher(\"\", 10)",
          "output": "\"\""
        }
      ],
  },
  {
    id: 7,
    difficulty: "hard",
    name: "py_cryptic_sorter",
    file: "py_cryptic_sorter.py",
    description: {
      en: "Write a function that sorts a list of strings according to multiple criteria:\n1. Primary sort: By string length (shortest first)\n2. Secondary sort: ASCII order, except letters are compared case-insensitively\n   (for strings of same length)\n3. Tertiary sort: By number of vowels (ascending, for same length and lexically equal)\n4. Equal strings will appear in the same order as in the input list.",
      de: "Schreibe eine Funktion, die eine Liste von Strings mit dreistufiger Priorität sortiert:\n1. Primär: nach Länge (aufsteigend)\n2. Sekundär: lexikographisch (alphabetisch, ohne Groß-/Kleinschreibung, aufsteigend)\n3. Tertiär: nach Anzahl der Vokale (aufsteigend bei gleicher Länge und lexikalischer Gleichheit)\n\nDie Funktion muss:\n- Leere Strings und leere Listen verarbeiten\n- Gemischte Groß-/Kleinschreibung (für Sortierung wie Kleinbuchstaben behandeln)\n- Sonderzeichen (für Vokalzählung ignorieren)",
      fr: "Écris une fonction qui trie une liste de chaînes avec une priorité à trois niveaux :\n1. Tri principal : par longueur (croissant)\n2. Tri secondaire : lexicographique (alphabétique, insensible à la casse, croissant)\n3. Tri tertiaire : par nombre de voyelles (croissant, si longueur et ordre lexicographique égaux)\n\nLa fonction doit gérer :\n- Chaînes vides et listes vides\n- Casses mixtes (traiter comme des minuscules pour le tri)\n- Caractères spéciaux (les ignorer pour compter les voyelles)",
      es: "Escribe una función que ordene una lista de cadenas con prioridad en tres niveles:\n1. Primario: por longitud (ascendente)\n2. Secundario: lexicográfico (alfabético, sin distinguir mayúsculas, ascendente)\n3. Terciario: por número de vocales (ascendente si la longitud y el orden léxico coinciden)\n\nLa función debe manejar:\n- Cadenas vacías y listas vacías\n- Mayúsculas y minúsculas mezcladas (tratar como minúsculas al ordenar)\n- Caracteres especiales (ignorarlos al contar vocales)",
      it: "Scrivi una funzione che ordini una lista di stringhe con priorità a tre livelli:\n1. Primario: per lunghezza (crescente)\n2. Secondario: lessicografico (alfabetico, case-insensitive, crescente)\n3. Terziario: per numero di vocali (crescente a parità di lunghezza e ordine lessicale)\n\nLa funzione deve gestire:\n- Stringhe vuote e liste vuote\n- Maiuscole e minuscole miste (per l’ordinamento trattare come minuscole)\n- Caratteri speciali (ignorarli nel conteggio delle vocali)",
    },
    signature: "def cryptic_sorter(strings: list[str]) -> list[str]:",
    examples: [
        {
          "input": "cryptic_sorter([\"apple\", \"cat\", \"banana\", \"dog\", \"elephant\"])",
          "output": "[\"cat\", \"dog\", \"apple\", \"banana\", \"elephant\"]"
        },
        {
          "input": "cryptic_sorter([\"aaa\", \"bbb\", \"AAA\", \"BBB\"])",
          "output": "[\"aaa\", \"AAA\", \"bbb\", \"BBB\"]"
        },
        {
          "input": "cryptic_sorter([\"hello\", \"world\", \"hi\", \"test\"])",
          "output": "[\"hi\", \"test\", \"hello\", \"world\"]"
        },
        {
          "input": "cryptic_sorter([])",
          "output": "[]"
        },
        {
          "input": "cryptic_sorter([\"\"])",
          "output": "[\"\"]"
        }
      ],
  },
  {
    id: 8,
    difficulty: "medium",
    name: "py_pattern_tracker",
    file: "py_pattern_tracker.py",
    description: {
      en: "Write a function that counts the number of valid consecutive digit pairs in a\nstring. A valid pair consists of two adjacent digits where the second digit\nis exactly one greater than the first digit. A 9 followed by a 0 is NOT a valid pair\nand only consider consecutive characters that are both digits (0-9).",
      de: "Schreibe eine Funktion, die die Anzahl gültiger aufeinanderfolgender Ziffernpaare in einem String zählt. Ein gültiges Paar besteht aus zwei benachbarten Ziffern, bei denen die zweite genau um eins größer ist als die erste. Eine 9 gefolgt von 0 ist KEIN gültiges Paar.",
      fr: "Écris une fonction qui compte le nombre de paires de chiffres consécutifs valides dans une chaîne. Une paire valide est formée de deux chiffres adjacents dont le second vaut exactement un de plus que le premier. Un 9 suivi d’un 0 n’est PAS une paire valide.",
      es: "Escribe una función que cuente cuántos pares consecutivos de dígitos válidos hay en una cadena. Un par válido son dos dígitos adyacentes donde el segundo es exactamente uno mayor que el primero. Un 9 seguido de 0 NO es un par válido.",
      it: "Scrivi una funzione che conti quante coppie consecutive di cifre valide ci sono in una stringa. Una coppia valida è formata da due cifre adiacenti in cui la seconda è esattamente uno più della prima. Un 9 seguito da 0 NON è una coppia valida.",
    },
    signature: "def pattern_tracker(text: str) -> int:",
    examples: [
        {
          "input": "pattern_tracker(\"123\")",
          "output": "2"
        },
        {
          "input": "pattern_tracker(\"12a34\")",
          "output": "2"
        },
        {
          "input": "pattern_tracker(\"987654321\")",
          "output": "0"
        },
        {
          "input": "pattern_tracker(\"01234567\")",
          "output": "7"
        },
        {
          "input": "pattern_tracker(\"abc\")",
          "output": "0"
        },
        {
          "input": "pattern_tracker(\"1a2b3c4\")",
          "output": "0"
        },
        {
          "input": "pattern_tracker(\"112233\")",
          "output": "2"
        }
      ],
  },
  {
    id: 9,
    difficulty: "medium",
    name: "py_string_sculptor",
    file: "py_string_sculptor.py",
    description: {
      en: "Write a function that transforms a string by alternating the case of alphabetic\ncharacters only. Non-alphabetic characters (spaces, digits, punctuation) stay as\nthey are and do not advance the alternation counter. The first alphabetic character\nshould be lowercase, the second uppercase, the third lowercase, and so on.",
      de: "Schreibe eine Funktion, die einen String transformiert, indem nur alphabetische Zeichen abwechselnd groß/klein geschrieben werden. Nicht-alphabetische Zeichen bleiben unverändert und zählen nicht für die Abwechslung. Das erste alphabetische Zeichen soll klein, das zweite groß, das dritte klein usw. sein.",
      fr: "Écris une fonction qui transforme une chaîne en alternant la casse des seuls caractères alphabétiques. Les autres caractères restent inchangés et ne comptent pas pour l’alternance. Le premier caractère alphabétique doit être en minuscule, le second en majuscule, le troisième en minuscule, etc.",
      es: "Escribe una función que transforme una cadena alternando mayúsculas y minúsculas solo en caracteres alfabéticos. Los demás permanecen igual y no cuentan para la alternancia. El primer carácter alfabético debe ser minúscula, el segundo mayúscula, el tercero minúscula, y así sucesivamente.",
      it: "Scrivi una funzione che trasformi una stringa alternando maiuscole e minuscole solo per i caratteri alfabetici. Gli altri restano invariati e non contano per l’alternanza. Il primo carattere alfabetico deve essere minuscolo, il secondo maiuscolo, il terzo minuscolo, e così via.",
    },
    signature: "def string_sculptor(text: str) -> str:",
    examples: [
        {
          "input": "string_sculptor(\"hello\")",
          "output": "\"hElLo\""
        },
        {
          "input": "string_sculptor(\"Hello World\")",
          "output": "\"hElLo WoRlD\""
        },
        {
          "input": "string_sculptor(\"aBc123def\")",
          "output": "\"aBc123DeF\""
        },
        {
          "input": "string_sculptor(\"Python3.9!\")",
          "output": "\"pYtHoN3.9!\""
        },
        {
          "input": "string_sculptor(\"\")",
          "output": "\"\""
        }
      ],
  },
  {
    id: 10,
    difficulty: "easy",
    name: "py_shadow_merge",
    file: "py_shadow_merge.py",
    description: {
      en: "Write a function that merges two sorted lists into one sorted list.",
      de: "Schreibe eine Funktion, die zwei sortierte Listen zu einer sortierten Liste zusammenführt.",
      fr: "Écris une fonction qui fusionne deux listes triées en une seule liste triée.",
      es: "Escribe una función que fusione dos listas ordenadas en una sola lista ordenada.",
      it: "Scrivi una funzione che unisca due liste ordinate in un’unica lista ordinata.",
    },
    signature: "def shadow_merge(list1: list[int], list2: list[int]) -> list[int]:",
    examples: [
        {
          "input": "shadow_merge([1, 3, 5], [2, 4, 6])",
          "output": "[1, 2, 3, 4, 5, 6]"
        },
        {
          "input": "shadow_merge([1, 2, 3], [4, 5, 6])",
          "output": "[1, 2, 3, 4, 5, 6]"
        },
        {
          "input": "shadow_merge([1], [2, 3, 4])",
          "output": "[1, 2, 3, 4]"
        },
        {
          "input": "shadow_merge([], [1, 2, 3])",
          "output": "[1, 2, 3]"
        },
        {
          "input": "shadow_merge([1, 1, 2], [1, 3, 3])",
          "output": "[1, 1, 1, 2, 3, 3]"
        }
      ],
  },
  {
    id: 11,
    difficulty: "medium",
    name: "py_twist_sequence",
    file: "py_twist_sequence.py",
    description: {
      en: "Write a function that rotates an array to the right by k positions, rotating right by k means the last k elements move to the front.",
      de: "Write a function that rotates an array to the right by k positions, rotating right by k means the last k elements move to the front.",
      fr: "Write a function that rotates an array to the right by k positions, rotating right by k means the last k elements move to the front.",
      es: "Write a function that rotates an array to the right by k positions, rotating right by k means the last k elements move to the front.",
      it: "Write a function that rotates an array to the right by k positions, rotating right by k means the last k elements move to the front.",
    },
    signature: "def twist_sequence(arr: list[int], k: int) -> list[int]:",
    examples: [
        {
          "input": "twist_sequence([1, 2, 3, 4, 5], 2)",
          "output": "[4, 5, 1, 2, 3]"
        },
        {
          "input": "twist_sequence([1, 2, 3], 1)",
          "output": "[3, 1, 2]"
        },
        {
          "input": "twist_sequence([1, 2, 3, 4], 0)",
          "output": "[1, 2, 3, 4]"
        },
        {
          "input": "twist_sequence([1, 2, 3], 5)",
          "output": "[2, 3, 1]"
        },
        {
          "input": "twist_sequence([], 3)",
          "output": "[]"
        }
      ],
  },
];
